name: dominhduong
description: A App of Do Minh Duong

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+11
# You just need to type "flutter pub run build_runner build --delete-conflicting-outputs" in Terminal, then press Enter :)))

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #firebase
#  firebase_analytics: ^9.0.5
#  firebase_messaging: 11.2.4
#  firebase_storage: 10.2.6
#  cloud_firestore: 3.1.7
#  firebase_core: 1.10.6
  scroll_snap_list: ^0.8.4
  flutter_rating_bar: ^4.0.0
  after_layout: ^1.1.0
  shimmer: ^2.0.0
  json_annotation: ^4.0.1
  retrofit: any
  provider: ^6.0.0
  dio: ^4.0.0
  pretty_dio_logger: ^1.1.1
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.17.0
  flutter_svg: ^0.23.0
  url_launcher: ^6.0.0
  flutter_html: ^2.1.5
  youtube_player_flutter: ^8.0.0
#  flutter_local_notifications: ^9.1.4
  flutter_progress_hud: ^2.0.0
  shared_preferences: ^2.0.11
  image_picker: ^0.8.5
  copy_with_extension: ^2.0.2
  responsive_framework: 0.1.5
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.0
  pin_code_fields: ^7.3.0
  flutter_datetime_picker: ^1.5.1
  permission_handler: ^8.3.0
  fluttertoast:
  flutter_app_badger:
  photo_view: ^0.13.0
#  flutter_sound: ^9.1.3
#  assets_audio_player: ^3.0.4+1
#  audio_session: ^0.1.6+1
#  audioplayers: ^0.20.1
  visibility_detector: ^0.2.2
  timeago: ^3.2.2
  dotted_border: ^2.0.0
  smooth_star_rating_null_safety: ^1.0.4+2
  app_launcher: ^1.0.0
#  emoji_picker_flutter: ^1.1.2
  file_picker: ^4.5.1
#  path_provider: ^2.0.9
#  android_path_provider: ^0.3.0
  modal_bottom_sheet: ^2.0.1
#  grouped_list: ^4.2.0
  flutter_downloader: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  retrofit_generator:
  build_runner:
  build_resolvers: ^2.0.4
  json_serializable: ^4.1.3
  copy_with_extension_gen: ^2.0.2
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1
  # flutter pub global run rename --appname "yourappname"[ --target android]
  rename: ^2.0.1

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#d7a444"
  image: "assets/ic_splash.png"

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path_android: "assets/ic_launcher_android.png"
  image_path_ios: "assets/ic_launcher_ios.png"
  adaptive_icon_background: "#d7a444"
  adaptive_icon_foreground: "assets/ic_launcher_android.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/fonts/Roboto-Bold.ttf
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/RobotoSlab-Bold.ttf
    - assets/fonts/RobotoSlab-Medium.ttf
    - assets/fonts/RobotoSlab-Regular.ttf
    - assets/fonts/UTM_Conestoga.ttf
    - assets/ic_launcher2.png
    - assets/ic_launcher_1.png
    - assets/ic_launcher_android.png
    - assets/ic_launcher_ios.png
    - assets/ic_splash.png
    - assets/icons/ic_account.svg
    - assets/icons/ic_back_x.svg
    - assets/icons/ic_booking.svg
    - assets/icons/ic_booking_circle.png
    - assets/icons/ic_booking_consultant.png
    - assets/icons/ic_booking_date.png
    - assets/icons/ic_booking_home.png
    - assets/icons/ic_box.svg
    - assets/icons/ic_calendar.svg
    - assets/icons/ic_calendar_dc.png
    - assets/icons/ic_calendar_outline.png
    - assets/icons/ic_calendar_time.svg
    - assets/icons/ic_chat_circle.png
    - assets/icons/ic_check_circle.svg
    - assets/icons/ic_close.svg
    - assets/icons/ic_consider_feedback.png
    - assets/icons/ic_consultant_circle.png
    - assets/icons/ic_dashboard.svg
    - assets/icons/ic_delete.svg
    - assets/icons/ic_dmd.svg
    - assets/icons/ic_doctor.svg
    - assets/icons/ic_documents.svg
    - assets/icons/ic_examination.png
    - assets/icons/ic_eye.svg
    - assets/icons/ic_eye_closed.svg
    - assets/icons/ic_eye_closed_2.svg
    - assets/icons/ic_facebook_feedback.png
    - assets/icons/ic_facebook_messenger.svg
    - assets/icons/ic_favorite.svg
    - assets/icons/ic_favorite_outlined.svg
    - assets/icons/ic_fb_message.svg
    - assets/icons/ic_floating_booking.svg
    - assets/icons/ic_friend_feedback.png
    - assets/icons/ic_heirloom_doctor.svg
    - assets/icons/ic_home.svg
    - assets/icons/ic_live_well.svg
    - assets/icons/ic_logo.svg
    - assets/icons/ic_logo_app.svg
    - assets/icons/ic_logo_app_dmd.png
    - assets/icons/ic_logo_apple.png
    - assets/icons/ic_logo_dmd.svg
    - assets/icons/ic_logo_facebook.png
    - assets/icons/ic_logo_google.png
    - assets/icons/ic_logo_zalo.png
    - assets/icons/ic_mail.svg
    - assets/icons/ic_medicine.png
    - assets/icons/ic_menu_bar.svg
    - assets/icons/ic_message.svg
    - assets/icons/ic_message_chat.svg
    - assets/icons/ic_message_circle.png
    - assets/icons/ic_messenger_svgrepo.svg
    - assets/icons/ic_news_circle.png
    - assets/icons/ic_newspaper_feedback.png
    - assets/icons/ic_no_feedback.png
    - assets/icons/ic_no_result.svg
    - assets/icons/ic_notification.svg
    - assets/icons/ic_order_medicine.png
    - assets/icons/ic_outline_arrow_forward.svg
    - assets/icons/ic_phone.svg
    - assets/icons/ic_phone1.svg
    - assets/icons/ic_phone_2.svg
    - assets/icons/ic_phone_circle.png
    - assets/icons/ic_phone_consultant.png
    - assets/icons/ic_phone_number.svg
    - assets/icons/ic_physical_therapy.png
    - assets/icons/ic_question_dc.png
    - assets/icons/ic_search.svg
    - assets/icons/ic_services.svg
    - assets/icons/ic_ship_medicine.png
    - assets/icons/ic_star.svg
    - assets/icons/ic_star_outline.svg
    - assets/icons/ic_success_feedback.png
    - assets/icons/ic_tv_feedback.png
    - assets/icons/ic_user.svg
    - assets/icons/ic_video.svg
    - assets/icons/ic_video_call.svg
    - assets/icons/ic_web_feedback.png
    - assets/icons/ic_write.svg
    - assets/icons/ic_yes_feedback.png
    - assets/icons/ic_zalo_circle.png
    - assets/icons/ic_zalo_feedback.png
    - assets/images/image_booking_success.svg
    - assets/images/image_close_popup.png
    - assets/images/image_download.png
    - assets/images/image_empty_data.png
    - assets/images/image_facebook_messenger.png
    - assets/images/image_folder.png
    - assets/images/image_login_background_1.png
    - assets/images/image_logo.png
    - assets/images/image_logo_2.svg
    - assets/images/image_logo_dmd.png
    - assets/images/image_medicine.png
    - assets/images/image_medicine_details.png
    - assets/images/image_messenger.png
    - assets/images/image_mp3.png
    - assets/images/image_mp4.png
    - assets/images/image_pdf.png
    - assets/images/image_people.svg
    - assets/images/image_powerpoint.png
    - assets/images/image_product_background.png
    - assets/images/image_support_success.svg
    - assets/images/image_txt.png
    - assets/images/image_word.png
    - assets/images/image_x.png
    - assets/images/image_zalo.png
    - assets/images/image_zip_file.png
    - assets/images/mimi1.gif
    - assets/images/mimi2.gif
    - assets/images/mimi3.gif
    - assets/images/mimi4.gif
    - assets/images/mimi5.gif
    - assets/images/mimi6.gif
    - assets/images/mimi7.gif
    - assets/images/mimi8.gif
    - assets/images/mimi9.gif
    - assets/images/placeholder.png
    - assets/translations/en.json
    - assets/translations/vi.json
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf
        - asset: assets/fonts/RobotoSlab-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Conestoga
      fonts:
        - asset: assets/fonts/UTM_Conestoga.ttf
          weight: 700


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
